apn/qos setting modified

diff --git a/apps/target/bin/sms_dmon_0624 b/apps/target/bin/sms_dmon_0624
--- a/apps/target/bin/sms_dmon_0624
+++ b/apps/target/bin/sms_dmon_0624
@@ -12,6 +12,9 @@ state_uninitialize=8
 state=state_uninitialize
 temp_state=0
 
+apn_text=""
+qos_text=""
+
 #set_sms_text()
 #{
 #	result=`mmd -p /dev/ttyS1 -c at+cmgf=1`
@@ -50,20 +53,23 @@ get_setting_sms()
 get_new_sms()
 {
 	`echo AT+CMGR=1 > /dev/ttyS1; sleep 0.1`
-	result=`/www/cgi-bin/scripts/get_new_sms.sh | awk '/CMGR/'`
+	result=`/www/cgi-bin/scripts/get_new_sms.sh | awk '/smsapn/'`
 	if [ -z "$result" ]
 	then
 		return 1
 	else
-		#echo $result
+		apn_text=`echo $result | sed -e 's/:/ /g' | awk '{ print $2 }'`
+		qos_text=`echo $result | sed -e 's/:/ /g' | awk '{ print $5 "," $3 "," $4 }'`
+		echo $apn_text
+		echo $qos_text
 		return 0
 	fi
 }
 
 setting_apn()
 {
-	result=`/www/cgi-bin/scripts/get_setting_sms.sh | awk '/smsapn/' | sed -e 's/:/ /g' | awk '{ print $2 }'`
-	`echo AT+CGDCONT=2,IP,$result,0.0.0.0,0,0 > /dev/ttyS1; sleep 0.1`
+#	result=`/www/cgi-bin/scripts/get_setting_sms.sh | awk '/smsapn/' | sed -e 's/:/ /g' | awk '{ print $2 }'`
+	`echo AT+CGDCONT=2,IP,$apn_text,0.0.0.0,0,0 > /dev/ttyS1; sleep 0.1`
 #	result2=`mmd -p /dev/ttyS1 -c at+cgdcont=1,IP,$result,0.0.0.0,0,0`
 #	if [ "$result2" = "OK" ]
 #	then
@@ -75,8 +81,8 @@ setting_apn()
 
 setting_qos()
 {
-	result=`/www/cgi-bin/scripts/get_setting_sms.sh | awk '/smsapn/' | sed -e 's/:/ /g' | awk '{print $5 "," $3 "," $4}'`
-	`echo AT+CGEQREQ=2,$result > /dev/ttyS1; sleep 0.1`
+#	result=`/www/cgi-bin/scripts/get_setting_sms.sh | awk '/smsapn/' | sed -e 's/:/ /g' | awk '{print $5 "," $3 "," $4}'`
+	`echo AT+CGEQREQ=2,$qos_text > /dev/ttyS1; sleep 0.1`
 #	result2=`mmd -p /dev/ttyS1 -c at+cgeqreq=1,$result`
 #	if [ "$result2" = "OK" ]
 #	then
@@ -163,32 +169,33 @@ do
 					get_new_sms
 					if [ $? -eq 0 ]
 					then
-						state=state_get_setting_sms
-					else
-						state=state_wait
-					fi
-				;;
-				state_get_setting_sms)
-					get_setting_sms
-					if [ $? -eq 0 ]
-					then
+#						state=state_get_setting_sms
 						state=state_setting_apn
 					else
-						state=state_delete_sms
-					fi
-				;;
-				state_cnum_sms)
-					send_sms_cnum
-					if [ $? -eq 0 ]
-					then
-						sleep 2
-						#echo "send ok"
-						state=state_delete_sms
-					else
-						#echo "send fail"
 						state=state_wait
 					fi
 				;;
+#					state_get_setting_sms)
+#					get_setting_sms
+#					if [ $? -eq 0 ]
+#					then
+#						state=state_setting_apn
+#					else
+#						state=state_delete_sms
+#					fi
+#				;;
+#				state_cnum_sms)
+#					send_sms_cnum
+#					if [ $? -eq 0 ]
+#					then
+#						sleep 2
+#						#echo "send ok"
+#						state=state_delete_sms
+#					else
+#						#echo "send fail"
+#						state=state_wait
+#					fi
+#				;;
 				state_setting_apn)
 					setting_apn
 					if [ $? -eq 0 ]
@@ -207,7 +214,7 @@ do
 					then
 						sleep 1
 						#echo "set qos ok"
-#	state=state_cnum_sms # 0605
+#						state=state_cnum_sms # 0605
 						`killall pppd`
 						state=state_delete_sms
 					else
@@ -225,6 +232,8 @@ do
 						#echo "fail"
 						state=state_wait
 					fi
+					apn_text=""
+					qos_text=""
 				;;
 				state_wait)
 					sleep 5 
